name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [ubuntu-18.04, windows-2019]

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3.0.2
      with:
        path: ""
    - name: Build
      run: cargo build --verbose
